### PR TITLE
Issue 384 fix cli script

### LINKED ISSUE #123: Resolve `rustup default stable` DX
Right now developer's have to run `rustup default stable` to add underlying rust-related CLI dependencies, whereafter that's cached inside of `.hermit/`. But this is less than ideal; hermit should bring these matters out of the box.

```
rs on  kendall/justfile [$] via 🦀 1.77.2
➜ rm -rf .hermit

rs on  kendall/justfile [$] via 🦀  took 20.1s
➜ cargo
error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.

rs on  kendall/justfile [$] via 🦀
➜ rustup default stable
info: syncing channel updates for 'stable-aarch64-apple-darwin'
info: latest update on 2024-04-09, rust version 1.77.2 (25ef9e3d8 2024-04-09)
info: downloading component 'cargo'
  6.2 MiB /   6.2 MiB (100 %)   6.0 MiB/s in  1s ETA:  0s
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 14.9 MiB /  14.9 MiB (100 %)   4.8 MiB/s in  3s ETA:  0s
info: downloading component 'rust-std'
 22.9 MiB /  22.9 MiB (100 %)   8.2 MiB/s in  2s ETA:  0s
info: downloading component 'rustc'
 54.1 MiB /  54.1 MiB (100 %)   8.4 MiB/s in  6s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
 14.9 MiB /  14.9 MiB (100 %)   3.5 MiB/s in  2s ETA:  0s
info: installing component 'rust-std'
 22.9 MiB /  22.9 MiB (100 %)  19.7 MiB/s in  1s ETA:  0s
info: installing component 'rustc'
 54.1 MiB /  54.1 MiB (100 %)  20.3 MiB/s in  2s ETA:  0s
info: installing component 'rustfmt'
info: default toolchain set to 'stable-aarch64-apple-darwin'

  stable-aarch64-apple-darwin installed - rustc 1.77.2 (25ef9e3d8 2024-04-09)


rs on  kendall/justfile [$] via 🦀 1.77.2 took 26.9s
➜ cargo
Rust's package manager

Usage: cargo [+toolchain] [OPTIONS] [COMMAND]
       cargo [+toolchain] [OPTIONS] -Zscript <MANIFEST_RS> [ARGS]...
```

### LINKED ISSUE #384: 🐛 Bug: Fix Web5 CLI Installation Script
# 🐛 Bug: Fix Web5 CLI Installation Script

## 🔍 Problem Description

The current installation script for the Web5 CLI is encountering errors during execution. Users are experiencing issues that prevent successful installation.

## 🚫 Current Behavior

When running the installation command:

```bash
curl -L https://raw.githubusercontent.com/TBD54566975/web5-rs/main/crates/web5_cli/install.sh | bash -s v0.0.4
```

Users encounter an error message, preventing successful installation:

```
rm: /tmp/web5-aarch64-apple-darwin: No such file or directory
```

## ✅ Expected Behavior

The installation script should:
1. Correctly download and install the Web5 CLI.
2. Handle cleanup operations without errors.
3. Provide clear success or error messages to the user.

## 💡 Proposed Solution

1. Implement proper error handling and checks throughout the script.
2. Ensure the cleanup operation only attempts to remove files that exist.
3. Add verbose output to help users understand what's happening during the installation process.

## 🔄 Steps to Reproduce

1. Run the following command:
   ```bash
   curl -L https://raw.githubusercontent.com/TBD54566975/web5-rs/main/crates/web5_cli/install.sh | bash -s v0.0.4
   ```
2. Observe the error messages.

## ℹ️ Additional Information

- 🖥️ OS: macOS (as indicated by the Darwin reference in the error message)
- 🏗️ Architecture: ARM64 (based on the aarch64 filename in the error)
- 🏷️ Web5 CLI version: v0.0.4

## 🚀 Possible Improvements

1. Add a check to verify if the download was successful before attempting to move or chmod the file.
2. Implement a function to check and create the `/usr/local/bin` directory if it doesn't exist.
3. Use a trap to ensure cleanup of temporary files even if the script exits prematurely.
4. Add more informative error messages to help users troubleshoot installation issues.

### PR DESCRIPTION
**Pull request by mushahidq**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description
This PR fixes Issue 384 to display error messages in Web5 CLI installation script and make it a bit more verbose. 

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Related Tickets & Documents

Resolves #384 

## Mobile & Desktop Screenshots/Recordings
image

## Added code snippets?
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

Updated installation script for web5cli

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by blackgirlbytes** [comment]
Awesome! I'll ping @KendallWeihe and other teammates to test this.

File: crates/web5_cli/install.sh [hunk 1]
```diff
@@ -28,12 +52,24 @@ case $OS in
...
+fi
 
 # give it executable permissions
 chmod +x /tmp/$FILENAME
 
 # Move the executable to /usr/local/bin
+if [ -d "/usr/local/bin" ]; then
+  echo "Creating /usr/local/bin"
+  mkdir /usr/local/bin
+fi
```
Comment (nitro-neal) [inline crates/web5_cli/install.sh:72]:
```suggestion
if [ ! -d "/usr/local/bin" ]; then
  echo "Creating /usr/local/bin"
  mkdir -p /usr/local/bin
fi
```

not sure what this woudl do on windows

**Review by nitro-neal — APPROVED** [review]
tested and working on my box, 

approving even though we have test vector failures as this is only changing the .sh script.

next time to get rid of compile errors you have to pull in the submodule test vectors by using:
```
git submodule update --init
```

Thank you very much!! 🥇
